languages:
  JavaScript: true
exclude_paths:
- "app/assets/javascripts/redactor.js"
- "src/assets/scripts/perfect-scrollbar.js"
- "src/assets/scripts/perfect-scrollbar.jquery.js"
- "src/assets/scripts/openseadragon.js"
- "build-conf/"
