# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71ba6ec5882a4bd5739d3998441a9cde09456ec77b0014cd33db6ec82234fab79f9d1dbb0d052fd4d35c9271549938584d235ff6efebd2b785df41f68f8c8265

test:
  secret_key_base: 000881351606d3d59242a3fd22944a2ffe45e004c53980d9434e623f8a6a34bcf7f97f1754da2d713a111679af5fe2fab6236be3aeafe2417d1ba2552f785d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
